title: MCP Proxy Wrapper
description: Proxy wrapper for Model Context Protocol (MCP) servers that provides a comprehensive hook system for intercepting and modifying tool calls
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Additional settings for Notion-like design
repository: crazyrabbitltc/mcp-proxy-wrapper
show_downloads: false
google_analytics: 

# Main navigation
nav:
  - title: Home
    url: /
    icon: fa-home
  - title: Extensible Hooks Design
    url: /implementation-plans/extensible-hooks-design
    icon: fa-plug
  - title: API Reference
    url: /api
    icon: fa-code
  - title: Examples
    url: /examples
    icon: fa-lightbulb
  - title: GitHub
    url: https://github.com/crazyrabbitltc/mcp-proxy-wrapper
    icon: fa-github

# Defaults for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
